version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    privileged: true
    ports:
      - "1883:1883"

    volumes:
      - /home/balbert/workspace/onix/mosquitto:/mosquitto
